### ISSUE TITLE
Todo in the alphanumeric keyboard

### ISSUE THREAD

**Issue by wil92** [wil92/keyboard-pcb#1]
# Todo list

- [ ] Add notation on the programmable pins.
- [x] Fix the issue with the USB connector's voltage.
- [x] Fix the issue with pins in the 32768 crystal.
- [x] Add test points for the important pins
  - [x] USB pins
  - [x] GND in the corner of the PCB
- [ ] Make an external circuit to enable the stm32 to programable mode (take this circuit out of the design).
- [x] Remove LEDs and related to them resistors.
- [x] Create jump to bypass hub controller and connect USB directly to the stm32 controller
- [ ] Id pin to GND
- [x] Fix the issue with the pins related to the 32.768 KHz quartz crystal component (current model MC-306)
- [ ] Add on led to the pcb
